### ISSUE TITLE
Configuration options?

### ISSUE THREAD

**Issue by renyuneyun** [vuquangtrong/simplify-theme#1]
I read the [documents](https://vuquangtrong.github.io/simplify-theme), but didn't find any hints on the configurations.
Does this imply that the theme does not allow customization at the moment?

**Comment by vuquangtrong** [comment]
Hi, 

you can see the configuration in **build** folder. It has [pelicanconf.py](https://github.com/vuquangtrong/simplify-theme/blob/master/build/pelicanconf.py) and [publishconf.py](https://github.com/vuquangtrong/simplify-theme/blob/master/build/publishconf.py).

**Comment by renyuneyun** [comment]
Thanks. I had a look at it and am trying to make some adjustments to suit my own needs.

By the way, is there a plan to support i18n of the theme? I see there is a `msg` macro in `base.html`, but didn't see using it (and not sure if it's actually related to i18n).
